/**
 * gen-plumb-enums.ts
 *
 * Codegen script: reads the four CLOSED plumb vocabularies from the TS
 * source-of-truth and writes Public/pcg/HaybaPlumbEnums.generated-mirror.h
 * into the Unreal plugin.
 *
 * Run:
 *   cd D:/Hackathons/hayba/mcp-tools/hayba-mcp
 *   npx tsx scripts/gen-plumb-enums.ts
 *
 * Or via npm:
 *   npm run gen:plumb-enums
 *
 * Idempotent: running twice produces no diff (SOURCE-HASH protects against
 * silent vocabulary drift between the TS contracts and the C++ mirror).
 */

import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// ── Import from the TS source-of-truth ───────────────────────────────────────
import { PRIMITIVES } from '../src/plumb/primitives.js';
import { GATE_ORDER } from '../src/plumb/contracts.js';

// JunctionType is a union-type alias — we derive the ordered values from the
// known discriminants in junction.ts: 'PORTAL' | 'BOOLEAN_UNION' | 'CLASH'.
// Order matches the source file declaration order.
const JUNCTION_IDS: string[] = ['PORTAL', 'BOOLEAN_UNION', 'CLASH'];

// EmitOp discriminants are listed in union order in contracts.ts.
const EMIT_OP_IDS: string[] = ['shell', 'asset', 'symbol', 'scatter', 'decal', 'fill'];

// ── Collect + validate ────────────────────────────────────────────────────────

const PRIMITIVE_IDS: string[] = PRIMITIVES.map((p) => p.id);

if (PRIMITIVE_IDS.length !== 13) {
  throw new Error(`Expected 13 primitives, got ${PRIMITIVE_IDS.length}: ${PRIMITIVE_IDS.join(', ')}`);
}
if (EMIT_OP_IDS.length !== 6) {
  throw new Error(`Expected 6 EmitOp kinds, got ${EMIT_OP_IDS.length}`);
}
if (JUNCTION_IDS.length !== 3) {
  throw new Error(`Expected 3 JunctionTypes, got ${JUNCTION_IDS.length}`);
}
if (GATE_ORDER.length !== 4) {
  throw new Error(`Expected 4 GATE_ORDER entries, got ${GATE_ORDER.length}`);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** snake_case or UPPER_CASE or lowercase → PascalCase for C++ enum names. */
function toPascalCase(id: string): string {
  return id
    .split(/[_\s]+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

/** Build a C++ TEXT("...") initializer list from an array of string ids. */
function buildTextArray(ids: string[]): string {
  return ids.map((id) => `    TEXT("${id}")`).join(',\n');
}

/** Compute a SHA-256 over the canonical serialization of the four source arrays. */
function computeSourceHash(): string {
  const canonical = JSON.stringify({
    PRIMITIVES: PRIMITIVE_IDS,
    EMIT_OP_IDS,
    JUNCTION_IDS,
    GATE_ORDER: [...GATE_ORDER],
  });
  return createHash('sha256').update(canonical, 'utf8').digest('hex');
}

// ── Generate enum names ───────────────────────────────────────────────────────

const primitiveEnumNames: string[] = PRIMITIVE_IDS.map(toPascalCase);
const emitOpEnumNames: string[] = EMIT_OP_IDS.map(toPascalCase);
const junctionEnumNames: string[] = JUNCTION_IDS.map(toPascalCase);

console.log(`Primitive IDs (${PRIMITIVE_IDS.length}): ${PRIMITIVE_IDS.join(', ')}`);
console.log(`Primitive enum names: ${primitiveEnumNames.join(', ')}`);
console.log(`EmitOp IDs (${EMIT_OP_IDS.length}): ${EMIT_OP_IDS.join(', ')}`);
console.log(`EmitOp enum names: ${emitOpEnumNames.join(', ')}`);
console.log(`JunctionType IDs (${JUNCTION_IDS.length}): ${JUNCTION_IDS.join(', ')}`);
console.log(`JunctionType enum names: ${junctionEnumNames.join(', ')}`);
console.log(`GATE_ORDER (${GATE_ORDER.length}): ${GATE_ORDER.join(', ')}`);

const sourceHash = computeSourceHash();
console.log(`SOURCE-HASH: ${sourceHash}`);

// ── Emit the header ───────────────────────────────────────────────────────────

// Script lives at: hayba-mcp/scripts/gen-plumb-enums.ts
// Target lives at: hayba/unreal/HaybaMCPToolkit/Source/HaybaMCPToolkit/Public/pcg/...
// Relative from the scripts/ dir: ../../../unreal/...
const OUTPUT_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../unreal/HaybaMCPToolkit/Source/HaybaMCPToolkit/Public/pcg/HaybaPlumbEnums.generated-mirror.h'
);

const header =
  `// GENERATED by scripts/gen-plumb-enums.ts from the TS plumb contracts. DO NOT EDIT BY HAND.\n` +
  `// SOURCE-HASH: ${sourceHash}\n` +
  `//\n` +
  `// Source-of-truth files:\n` +
  `//   D:/Hackathons/hayba/mcp-tools/hayba-mcp/src/plumb/primitives.ts   — PRIMITIVES array (13)\n` +
  `//   D:/Hackathons/hayba/mcp-tools/hayba-mcp/src/plumb/contracts.ts    — EmitOp union + GATE_ORDER\n` +
  `//   D:/Hackathons/hayba/mcp-tools/hayba-mcp/src/plumb/junction.ts     — JunctionType union\n` +
  `//\n` +
  `// To regenerate: cd D:/Hackathons/hayba/mcp-tools/hayba-mcp && npm run gen:plumb-enums\n` +
  `// "Plumb is the single rule authority" -- no C++ node may reference a value not in these enums.\n` +
  `\n` +
  `#pragma once\n` +
  `\n` +
  `#include "CoreMinimal.h"\n` +
  `\n` +
  `// -- EHaybaPrimitive (13 entries, order = PRIMITIVES array order in primitives.ts) --\n` +
  `\n` +
  `enum class EHaybaPrimitive : uint8\n` +
  `{\n` +
  `    ${primitiveEnumNames.join(',\n    ')},\n` +
  `};\n` +
  `\n` +
  `static const TCHAR* const GHaybaPrimitiveIds[] =\n` +
  `{\n` +
  `${buildTextArray(PRIMITIVE_IDS)},\n` +
  `};\n` +
  `\n` +
  `// -- EHaybaEmitOp (6 entries, order = EmitOp union discriminant order in contracts.ts) --\n` +
  `\n` +
  `enum class EHaybaEmitOp : uint8\n` +
  `{\n` +
  `    ${emitOpEnumNames.join(',\n    ')},\n` +
  `};\n` +
  `\n` +
  `static const TCHAR* const GHaybaEmitOpIds[] =\n` +
  `{\n` +
  `${buildTextArray(EMIT_OP_IDS)},\n` +
  `};\n` +
  `\n` +
  `// -- EHaybaJunctionType (3 entries, order = PORTAL | BOOLEAN_UNION | CLASH in junction.ts) --\n` +
  `\n` +
  `enum class EHaybaJunctionType : uint8\n` +
  `{\n` +
  `    ${junctionEnumNames.join(',\n    ')},\n` +
  `};\n` +
  `\n` +
  `static const TCHAR* const GHaybaJunctionTypeIds[] =\n` +
  `{\n` +
  `${buildTextArray(JUNCTION_IDS)},\n` +
  `};\n` +
  `\n` +
  `// -- GHaybaGateOrder (4 entries, order IS the hard-fail short-circuit order in contracts.ts) --\n` +
  `\n` +
  `static const TCHAR* const GHaybaGateOrder[] =\n` +
  `{\n` +
  `${buildTextArray([...GATE_ORDER])},\n` +
  `};\n` +
  `\n` +
  `// -- Free helpers: return false for unknown id (callers turn this into a cook-time error) --\n` +
  `\n` +
  `inline bool HaybaIsKnownPrimitiveId(const FString& Id)\n` +
  `{\n` +
  `    for (const TCHAR* const Known : GHaybaPrimitiveIds)\n` +
  `    {\n` +
  `        if (Id == Known) return true;\n` +
  `    }\n` +
  `    return false;\n` +
  `}\n` +
  `\n` +
  `inline bool HaybaIsKnownEmitOp(const FString& Id)\n` +
  `{\n` +
  `    for (const TCHAR* const Known : GHaybaEmitOpIds)\n` +
  `    {\n` +
  `        if (Id == Known) return true;\n` +
  `    }\n` +
  `    return false;\n` +
  `}\n` +
  `\n` +
  `inline bool HaybaIsKnownJunctionType(const FString& Id)\n` +
  `{\n` +
  `    for (const TCHAR* const Known : GHaybaJunctionTypeIds)\n` +
  `    {\n` +
  `        if (Id == Known) return true;\n` +
  `    }\n` +
  `    return false;\n` +
  `}\n`;

writeFileSync(OUTPUT_PATH, header, 'utf8');
console.log(`\nWrote: ${OUTPUT_PATH}`);
console.log('Done. Run again to verify idempotency (expect no diff).');
