// GENERATED by scripts/gen-plumb-enums.ts from the TS plumb contracts. DO NOT EDIT BY HAND.
// SOURCE-HASH: 73b8eba3f73ee7693e105918f608724bf5c80372caae47b45289323d4ef146a0
//
// Source-of-truth files:
//   D:/Hackathons/hayba/mcp-tools/hayba-mcp/src/plumb/primitives.ts   — PRIMITIVES array (13)
//   D:/Hackathons/hayba/mcp-tools/hayba-mcp/src/plumb/contracts.ts    — EmitOp union + GATE_ORDER
//   D:/Hackathons/hayba/mcp-tools/hayba-mcp/src/plumb/junction.ts     — JunctionType union
//
// To regenerate: cd D:/Hackathons/hayba/mcp-tools/hayba-mcp && npm run gen:plumb-enums
// "Plumb is the single rule authority" -- no C++ node may reference a value not in these enums.

#pragma once

#include "CoreMinimal.h"

// -- EHaybaPrimitive (13 entries, order = PRIMITIVES array order in primitives.ts) --

enum class EHaybaPrimitive : uint8
{
    Grounded,
    Clearance,
    SupportMargin,
    Upright,
    ScaleRange,
    CountPerM2,
    Proximity,
    InsideOutside,
    Facing,
    AffordanceClear,
    SurfaceContact,
    Presence,
    MaxStraightRun,
};

static const TCHAR* const GHaybaPrimitiveIds[] =
{
    TEXT("grounded"),
    TEXT("clearance"),
    TEXT("support_margin"),
    TEXT("upright"),
    TEXT("scale_range"),
    TEXT("count_per_m2"),
    TEXT("proximity"),
    TEXT("inside_outside"),
    TEXT("facing"),
    TEXT("affordance_clear"),
    TEXT("surface_contact"),
    TEXT("presence"),
    TEXT("max_straight_run"),
};

// -- EHaybaEmitOp (6 entries, order = EmitOp union discriminant order in contracts.ts) --

enum class EHaybaEmitOp : uint8
{
    Shell,
    Asset,
    Symbol,
    Scatter,
    Decal,
    Fill,
};

static const TCHAR* const GHaybaEmitOpIds[] =
{
    TEXT("shell"),
    TEXT("asset"),
    TEXT("symbol"),
    TEXT("scatter"),
    TEXT("decal"),
    TEXT("fill"),
};

// -- EHaybaJunctionType (3 entries, order = PORTAL | BOOLEAN_UNION | CLASH in junction.ts) --

enum class EHaybaJunctionType : uint8
{
    Portal,
    BooleanUnion,
    Clash,
};

static const TCHAR* const GHaybaJunctionTypeIds[] =
{
    TEXT("PORTAL"),
    TEXT("BOOLEAN_UNION"),
    TEXT("CLASH"),
};

// -- GHaybaGateOrder (4 entries, order IS the hard-fail short-circuit order in contracts.ts) --

static const TCHAR* const GHaybaGateOrder[] =
{
    TEXT("collision"),
    TEXT("stability"),
    TEXT("constraints"),
    TEXT("reach"),
};

// -- Free helpers: return false for unknown id (callers turn this into a cook-time error) --

inline bool HaybaIsKnownPrimitiveId(const FString& Id)
{
    for (const TCHAR* const Known : GHaybaPrimitiveIds)
    {
        if (Id == Known) return true;
    }
    return false;
}

inline bool HaybaIsKnownEmitOp(const FString& Id)
{
    for (const TCHAR* const Known : GHaybaEmitOpIds)
    {
        if (Id == Known) return true;
    }
    return false;
}

inline bool HaybaIsKnownJunctionType(const FString& Id)
{
    for (const TCHAR* const Known : GHaybaJunctionTypeIds)
    {
        if (Id == Known) return true;
    }
    return false;
}
